#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 1) readonly buffer IsALeafBuffer {
    int isALeafBuffer[];
};

layout(std430, binding = 2) buffer OutputBuffer {
    int outputBuffer[];
};

bool amIInsideALeaf(uint index) {
    return isALeafBuffer[index] > 0;
}

uniform int char_to_find;

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (inputBuffer[index] == char_to_find && amIInsideALeaf(index)) {
        outputBuffer[index] = 1;
    } else {
        outputBuffer[index] = 0;
    }
}
