#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 1) readonly buffer LeafEdgeCounter {
    int leafEdgeCounter[];
};

layout(std430, binding = 2) readonly buffer Transformations {
    mat4 transformations[];
};

layout(std430, binding = 3) buffer LeafPosition {
    vec4 leafPosition[];
};

layout(std430, binding = 4) buffer LeafIndex {
    uint leafIndex[];
};

layout(std430, binding = 5) readonly buffer IsALeafBuffer {
    int isALeafBuffer[];
};

uniform int char_of_leaf_edge;
uniform int alternative_char_of_leaf_edge;
uniform int second_alternative_char_of_leaf_edge;
uniform mat4 common_turtle_matrix;
uniform uint reset_index_value;

bool isCharOfLeafEdge(int letter, int index) {
    return (letter == char_of_leaf_edge && isALeafBuffer[index] > 0)
        || letter == alternative_char_of_leaf_edge
        || letter == second_alternative_char_of_leaf_edge;
}

bool isReset(int letter) {
    return letter == second_alternative_char_of_leaf_edge;
}

void main() {
    int index = int(gl_GlobalInvocationID.x);
    int letter = inputBuffer[index];

    if (!isCharOfLeafEdge(letter, index)) {
        return;
    }

    // what is the index of my leaf edge in the leaf edge counter
    int myLeafEdgeIndex = leafEdgeCounter[index] - 1;

    if (isReset(letter)) {
        leafPosition[myLeafEdgeIndex] = vec4(0.0, 0.0, 0.0, 0.0);
        leafIndex[myLeafEdgeIndex] = reset_index_value;
    } else {
        mat4 myTransofrmation = transformations[index] * common_turtle_matrix;

        // last row of the matrix is my position (myTransofrmation[3] is the last column!!!, and I need last ROW)
        leafPosition[myLeafEdgeIndex] = vec4(myTransofrmation[0][3], myTransofrmation[1][3], myTransofrmation[2][3], myTransofrmation[3][3]);
        leafIndex[myLeafEdgeIndex] = uint(index);
    }
}
