#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 1) readonly buffer LeafEdgeCounter {
    int leafEdgeCounter[];
};

layout(std430, binding = 2) readonly buffer LeafBeginCounter {
    int leafBeginCounter[];
};

layout(std430, binding = 3) readonly buffer LookBackTable {
    int lookBackTable[];
};

layout(std430, binding = 4) buffer LeafMetaSize {
    int leafMetaSize[];
};

layout(std430, binding = 5) buffer LeafMetaOffset {
    int leafMetaOffset[];
};

uniform int char_of_leaf_end;

void main() {
    int index = int(gl_GlobalInvocationID.x);

    int letter = inputBuffer[index];
    if (letter != char_of_leaf_end) {
        return;
    }

    int myMatchingLeafBegin = index + lookBackTable[index];
    int myLeafEdgeCount = leafEdgeCounter[index];
    // we include one for the leaf begin
    int myMatchingLeafBeginEdgeCount = leafEdgeCounter[myMatchingLeafBegin] - 1;

    // how many leafs are there before me (excluding me)
    int myLeafPositionInMeta = leafBeginCounter[myMatchingLeafBegin] - 1;

    leafMetaSize[myLeafPositionInMeta] = myLeafEdgeCount - myMatchingLeafBeginEdgeCount;
    leafMetaOffset[myLeafPositionInMeta] = myMatchingLeafBeginEdgeCount;
}
