/* File generated by the BNF Converter (bnfc 2.9.5). */

//C++ Abstract Syntax Implementation.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"

/********************   ASTLSectionSeparator    ********************/
ASTLSectionSeparator::ASTLSectionSeparator()
{

}

ASTLSectionSeparator::ASTLSectionSeparator(const ASTLSectionSeparator & other)
{

}

ASTLSectionSeparator &ASTLSectionSeparator::operator=(const ASTLSectionSeparator & other)
{
  ASTLSectionSeparator tmp(other);
  swap(tmp);
  return *this;
}

void ASTLSectionSeparator::swap(ASTLSectionSeparator & other)
{

}

ASTLSectionSeparator::~ASTLSectionSeparator()
{

}

void ASTLSectionSeparator::accept(Visitor *v)
{
  v->visitASTLSectionSeparator(this);
}

ASTLSectionSeparator *ASTLSectionSeparator::clone() const
{
  return new ASTLSectionSeparator(*this);
}



/********************   ASTLProgram    ********************/
ASTLProgram::ASTLProgram(ASTProperties *p1, ASTSectionSeparator *p2, ASTAxiom *p3, ASTSectionSeparator *p4, ASTRules *p5)
{
  astproperties_ = p1;
  astsectionseparator_1 = p2;
  astaxiom_ = p3;
  astsectionseparator_2 = p4;
  astrules_ = p5;

}

ASTLProgram::ASTLProgram(const ASTLProgram & other)
{
  astproperties_ = other.astproperties_->clone();
  astsectionseparator_1 = other.astsectionseparator_1->clone();
  astaxiom_ = other.astaxiom_->clone();
  astsectionseparator_2 = other.astsectionseparator_2->clone();
  astrules_ = other.astrules_->clone();

}

ASTLProgram &ASTLProgram::operator=(const ASTLProgram & other)
{
  ASTLProgram tmp(other);
  swap(tmp);
  return *this;
}

void ASTLProgram::swap(ASTLProgram & other)
{
  std::swap(astproperties_, other.astproperties_);
  std::swap(astsectionseparator_1, other.astsectionseparator_1);
  std::swap(astaxiom_, other.astaxiom_);
  std::swap(astsectionseparator_2, other.astsectionseparator_2);
  std::swap(astrules_, other.astrules_);

}

ASTLProgram::~ASTLProgram()
{
  delete(astproperties_);
  delete(astsectionseparator_1);
  delete(astaxiom_);
  delete(astsectionseparator_2);
  delete(astrules_);

}

void ASTLProgram::accept(Visitor *v)
{
  v->visitASTLProgram(this);
}

ASTLProgram *ASTLProgram::clone() const
{
  return new ASTLProgram(*this);
}



/********************   ASTLIProperty    ********************/
ASTLIProperty::ASTLIProperty(Prod p1, Integer p2)
{
  prod_ = p1;
  integer_ = p2;

}

ASTLIProperty::ASTLIProperty(const ASTLIProperty & other)
{
  prod_ = other.prod_;
  integer_ = other.integer_;

}

ASTLIProperty &ASTLIProperty::operator=(const ASTLIProperty & other)
{
  ASTLIProperty tmp(other);
  swap(tmp);
  return *this;
}

void ASTLIProperty::swap(ASTLIProperty & other)
{
  std::swap(prod_, other.prod_);
  std::swap(integer_, other.integer_);

}

ASTLIProperty::~ASTLIProperty()
{

}

void ASTLIProperty::accept(Visitor *v)
{
  v->visitASTLIProperty(this);
}

ASTLIProperty *ASTLIProperty::clone() const
{
  return new ASTLIProperty(*this);
}



/********************   ASTLDProperty    ********************/
ASTLDProperty::ASTLDProperty(Prod p1, Double p2)
{
  prod_ = p1;
  double_ = p2;

}

ASTLDProperty::ASTLDProperty(const ASTLDProperty & other)
{
  prod_ = other.prod_;
  double_ = other.double_;

}

ASTLDProperty &ASTLDProperty::operator=(const ASTLDProperty & other)
{
  ASTLDProperty tmp(other);
  swap(tmp);
  return *this;
}

void ASTLDProperty::swap(ASTLDProperty & other)
{
  std::swap(prod_, other.prod_);
  std::swap(double_, other.double_);

}

ASTLDProperty::~ASTLDProperty()
{

}

void ASTLDProperty::accept(Visitor *v)
{
  v->visitASTLDProperty(this);
}

ASTLDProperty *ASTLDProperty::clone() const
{
  return new ASTLDProperty(*this);
}



/********************   ASTIgnore    ********************/
ASTIgnore::ASTIgnore(Prod p1)
{
  prod_ = p1;

}

ASTIgnore::ASTIgnore(const ASTIgnore & other)
{
  prod_ = other.prod_;

}

ASTIgnore &ASTIgnore::operator=(const ASTIgnore & other)
{
  ASTIgnore tmp(other);
  swap(tmp);
  return *this;
}

void ASTIgnore::swap(ASTIgnore & other)
{
  std::swap(prod_, other.prod_);

}

ASTIgnore::~ASTIgnore()
{

}

void ASTIgnore::accept(Visitor *v)
{
  v->visitASTIgnore(this);
}

ASTIgnore *ASTIgnore::clone() const
{
  return new ASTIgnore(*this);
}



/********************   ASTLProperties    ********************/
ASTLProperties::ASTLProperties(ListASTProperty *p1)
{
  listastproperty_ = p1;

}

ASTLProperties::ASTLProperties(const ASTLProperties & other)
{
  listastproperty_ = other.listastproperty_->clone();

}

ASTLProperties &ASTLProperties::operator=(const ASTLProperties & other)
{
  ASTLProperties tmp(other);
  swap(tmp);
  return *this;
}

void ASTLProperties::swap(ASTLProperties & other)
{
  std::swap(listastproperty_, other.listastproperty_);

}

ASTLProperties::~ASTLProperties()
{
  delete(listastproperty_);

}

void ASTLProperties::accept(Visitor *v)
{
  v->visitASTLProperties(this);
}

ASTLProperties *ASTLProperties::clone() const
{
  return new ASTLProperties(*this);
}



/********************   ASTLAxiom    ********************/
ASTLAxiom::ASTLAxiom(Prod p1)
{
  prod_ = p1;

}

ASTLAxiom::ASTLAxiom(const ASTLAxiom & other)
{
  prod_ = other.prod_;

}

ASTLAxiom &ASTLAxiom::operator=(const ASTLAxiom & other)
{
  ASTLAxiom tmp(other);
  swap(tmp);
  return *this;
}

void ASTLAxiom::swap(ASTLAxiom & other)
{
  std::swap(prod_, other.prod_);

}

ASTLAxiom::~ASTLAxiom()
{

}

void ASTLAxiom::accept(Visitor *v)
{
  v->visitASTLAxiom(this);
}

ASTLAxiom *ASTLAxiom::clone() const
{
  return new ASTLAxiom(*this);
}



/********************   ASTLRule    ********************/
ASTLRule::ASTLRule(Prod p1, Prod p2)
{
  prod_1 = p1;
  prod_2 = p2;

}

ASTLRule::ASTLRule(const ASTLRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;

}

ASTLRule &ASTLRule::operator=(const ASTLRule & other)
{
  ASTLRule tmp(other);
  swap(tmp);
  return *this;
}

void ASTLRule::swap(ASTLRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);

}

ASTLRule::~ASTLRule()
{

}

void ASTLRule::accept(Visitor *v)
{
  v->visitASTLRule(this);
}

ASTLRule *ASTLRule::clone() const
{
  return new ASTLRule(*this);
}



/********************   ASTLLeftRule    ********************/
ASTLLeftRule::ASTLLeftRule(Prod p1, Prod p2, Prod p3)
{
  prod_1 = p1;
  prod_2 = p2;
  prod_3 = p3;

}

ASTLLeftRule::ASTLLeftRule(const ASTLLeftRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;
  prod_3 = other.prod_3;

}

ASTLLeftRule &ASTLLeftRule::operator=(const ASTLLeftRule & other)
{
  ASTLLeftRule tmp(other);
  swap(tmp);
  return *this;
}

void ASTLLeftRule::swap(ASTLLeftRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);
  std::swap(prod_3, other.prod_3);

}

ASTLLeftRule::~ASTLLeftRule()
{

}

void ASTLLeftRule::accept(Visitor *v)
{
  v->visitASTLLeftRule(this);
}

ASTLLeftRule *ASTLLeftRule::clone() const
{
  return new ASTLLeftRule(*this);
}



/********************   ASTLRightRule    ********************/
ASTLRightRule::ASTLRightRule(Prod p1, Prod p2, Prod p3)
{
  prod_1 = p1;
  prod_2 = p2;
  prod_3 = p3;

}

ASTLRightRule::ASTLRightRule(const ASTLRightRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;
  prod_3 = other.prod_3;

}

ASTLRightRule &ASTLRightRule::operator=(const ASTLRightRule & other)
{
  ASTLRightRule tmp(other);
  swap(tmp);
  return *this;
}

void ASTLRightRule::swap(ASTLRightRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);
  std::swap(prod_3, other.prod_3);

}

ASTLRightRule::~ASTLRightRule()
{

}

void ASTLRightRule::accept(Visitor *v)
{
  v->visitASTLRightRule(this);
}

ASTLRightRule *ASTLRightRule::clone() const
{
  return new ASTLRightRule(*this);
}



/********************   ASTLBothRule    ********************/
ASTLBothRule::ASTLBothRule(Prod p1, Prod p2, Prod p3, Prod p4)
{
  prod_1 = p1;
  prod_2 = p2;
  prod_3 = p3;
  prod_4 = p4;

}

ASTLBothRule::ASTLBothRule(const ASTLBothRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;
  prod_3 = other.prod_3;
  prod_4 = other.prod_4;

}

ASTLBothRule &ASTLBothRule::operator=(const ASTLBothRule & other)
{
  ASTLBothRule tmp(other);
  swap(tmp);
  return *this;
}

void ASTLBothRule::swap(ASTLBothRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);
  std::swap(prod_3, other.prod_3);
  std::swap(prod_4, other.prod_4);

}

ASTLBothRule::~ASTLBothRule()
{

}

void ASTLBothRule::accept(Visitor *v)
{
  v->visitASTLBothRule(this);
}

ASTLBothRule *ASTLBothRule::clone() const
{
  return new ASTLBothRule(*this);
}



/********************   ASTLRules    ********************/
ASTLRules::ASTLRules(ListASTRule *p1)
{
  listastrule_ = p1;

}

ASTLRules::ASTLRules(const ASTLRules & other)
{
  listastrule_ = other.listastrule_->clone();

}

ASTLRules &ASTLRules::operator=(const ASTLRules & other)
{
  ASTLRules tmp(other);
  swap(tmp);
  return *this;
}

void ASTLRules::swap(ASTLRules & other)
{
  std::swap(listastrule_, other.listastrule_);

}

ASTLRules::~ASTLRules()
{
  delete(listastrule_);

}

void ASTLRules::accept(Visitor *v)
{
  v->visitASTLRules(this);
}

ASTLRules *ASTLRules::clone() const
{
  return new ASTLRules(*this);
}




/********************   ListASTProperty    ********************/

void ListASTProperty::accept(Visitor *v)
{
  v->visitListASTProperty(this);
}

ListASTProperty *ListASTProperty::clone() const
{
  return new ListASTProperty(*this);
}

ListASTProperty* consListASTProperty(ASTProperty* x, ListASTProperty* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListASTRule    ********************/

void ListASTRule::accept(Visitor *v)
{
  v->visitListASTRule(this);
}

ListASTRule *ListASTRule::clone() const
{
  return new ListASTRule(*this);
}

ListASTRule* consListASTRule(ASTRule* x, ListASTRule* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}





