/* File generated by the BNF Converter (bnfc 2.9.5). */

//C++ Abstract Syntax Implementation.
#include <algorithm>
#include <string>
#include <vector>
#include "Absyn.H"

/********************   LSectionSeparator    ********************/
LSectionSeparator::LSectionSeparator()
{

}

LSectionSeparator::LSectionSeparator(const LSectionSeparator & other)
{

}

LSectionSeparator &LSectionSeparator::operator=(const LSectionSeparator & other)
{
  LSectionSeparator tmp(other);
  swap(tmp);
  return *this;
}

void LSectionSeparator::swap(LSectionSeparator & other)
{

}

LSectionSeparator::~LSectionSeparator()
{

}

void LSectionSeparator::accept(Visitor *v)
{
  v->visitLSectionSeparator(this);
}

LSectionSeparator *LSectionSeparator::clone() const
{
  return new LSectionSeparator(*this);
}



/********************   LProgram    ********************/
LProgram::LProgram(Properties *p1, SectionSeparator *p2, Axiom *p3, SectionSeparator *p4, Rules *p5)
{
  properties_ = p1;
  sectionseparator_1 = p2;
  axiom_ = p3;
  sectionseparator_2 = p4;
  rules_ = p5;

}

LProgram::LProgram(const LProgram & other)
{
  properties_ = other.properties_->clone();
  sectionseparator_1 = other.sectionseparator_1->clone();
  axiom_ = other.axiom_->clone();
  sectionseparator_2 = other.sectionseparator_2->clone();
  rules_ = other.rules_->clone();

}

LProgram &LProgram::operator=(const LProgram & other)
{
  LProgram tmp(other);
  swap(tmp);
  return *this;
}

void LProgram::swap(LProgram & other)
{
  std::swap(properties_, other.properties_);
  std::swap(sectionseparator_1, other.sectionseparator_1);
  std::swap(axiom_, other.axiom_);
  std::swap(sectionseparator_2, other.sectionseparator_2);
  std::swap(rules_, other.rules_);

}

LProgram::~LProgram()
{
  delete(properties_);
  delete(sectionseparator_1);
  delete(axiom_);
  delete(sectionseparator_2);
  delete(rules_);

}

void LProgram::accept(Visitor *v)
{
  v->visitLProgram(this);
}

LProgram *LProgram::clone() const
{
  return new LProgram(*this);
}



/********************   LIProperty    ********************/
LIProperty::LIProperty(Prod p1, Integer p2)
{
  prod_ = p1;
  integer_ = p2;

}

LIProperty::LIProperty(const LIProperty & other)
{
  prod_ = other.prod_;
  integer_ = other.integer_;

}

LIProperty &LIProperty::operator=(const LIProperty & other)
{
  LIProperty tmp(other);
  swap(tmp);
  return *this;
}

void LIProperty::swap(LIProperty & other)
{
  std::swap(prod_, other.prod_);
  std::swap(integer_, other.integer_);

}

LIProperty::~LIProperty()
{

}

void LIProperty::accept(Visitor *v)
{
  v->visitLIProperty(this);
}

LIProperty *LIProperty::clone() const
{
  return new LIProperty(*this);
}



/********************   LDProperty    ********************/
LDProperty::LDProperty(Prod p1, Double p2)
{
  prod_ = p1;
  double_ = p2;

}

LDProperty::LDProperty(const LDProperty & other)
{
  prod_ = other.prod_;
  double_ = other.double_;

}

LDProperty &LDProperty::operator=(const LDProperty & other)
{
  LDProperty tmp(other);
  swap(tmp);
  return *this;
}

void LDProperty::swap(LDProperty & other)
{
  std::swap(prod_, other.prod_);
  std::swap(double_, other.double_);

}

LDProperty::~LDProperty()
{

}

void LDProperty::accept(Visitor *v)
{
  v->visitLDProperty(this);
}

LDProperty *LDProperty::clone() const
{
  return new LDProperty(*this);
}



/********************   LProperties    ********************/
LProperties::LProperties(ListProperty *p1)
{
  listproperty_ = p1;

}

LProperties::LProperties(const LProperties & other)
{
  listproperty_ = other.listproperty_->clone();

}

LProperties &LProperties::operator=(const LProperties & other)
{
  LProperties tmp(other);
  swap(tmp);
  return *this;
}

void LProperties::swap(LProperties & other)
{
  std::swap(listproperty_, other.listproperty_);

}

LProperties::~LProperties()
{
  delete(listproperty_);

}

void LProperties::accept(Visitor *v)
{
  v->visitLProperties(this);
}

LProperties *LProperties::clone() const
{
  return new LProperties(*this);
}



/********************   LAxiom    ********************/
LAxiom::LAxiom(Prod p1)
{
  prod_ = p1;

}

LAxiom::LAxiom(const LAxiom & other)
{
  prod_ = other.prod_;

}

LAxiom &LAxiom::operator=(const LAxiom & other)
{
  LAxiom tmp(other);
  swap(tmp);
  return *this;
}

void LAxiom::swap(LAxiom & other)
{
  std::swap(prod_, other.prod_);

}

LAxiom::~LAxiom()
{

}

void LAxiom::accept(Visitor *v)
{
  v->visitLAxiom(this);
}

LAxiom *LAxiom::clone() const
{
  return new LAxiom(*this);
}



/********************   LRule    ********************/
LRule::LRule(Prod p1, Prod p2)
{
  prod_1 = p1;
  prod_2 = p2;

}

LRule::LRule(const LRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;

}

LRule &LRule::operator=(const LRule & other)
{
  LRule tmp(other);
  swap(tmp);
  return *this;
}

void LRule::swap(LRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);

}

LRule::~LRule()
{

}

void LRule::accept(Visitor *v)
{
  v->visitLRule(this);
}

LRule *LRule::clone() const
{
  return new LRule(*this);
}



/********************   LLeftRule    ********************/
LLeftRule::LLeftRule(Prod p1, Prod p2, Prod p3)
{
  prod_1 = p1;
  prod_2 = p2;
  prod_3 = p3;

}

LLeftRule::LLeftRule(const LLeftRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;
  prod_3 = other.prod_3;

}

LLeftRule &LLeftRule::operator=(const LLeftRule & other)
{
  LLeftRule tmp(other);
  swap(tmp);
  return *this;
}

void LLeftRule::swap(LLeftRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);
  std::swap(prod_3, other.prod_3);

}

LLeftRule::~LLeftRule()
{

}

void LLeftRule::accept(Visitor *v)
{
  v->visitLLeftRule(this);
}

LLeftRule *LLeftRule::clone() const
{
  return new LLeftRule(*this);
}



/********************   LRightRule    ********************/
LRightRule::LRightRule(Prod p1, Prod p2, Prod p3)
{
  prod_1 = p1;
  prod_2 = p2;
  prod_3 = p3;

}

LRightRule::LRightRule(const LRightRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;
  prod_3 = other.prod_3;

}

LRightRule &LRightRule::operator=(const LRightRule & other)
{
  LRightRule tmp(other);
  swap(tmp);
  return *this;
}

void LRightRule::swap(LRightRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);
  std::swap(prod_3, other.prod_3);

}

LRightRule::~LRightRule()
{

}

void LRightRule::accept(Visitor *v)
{
  v->visitLRightRule(this);
}

LRightRule *LRightRule::clone() const
{
  return new LRightRule(*this);
}



/********************   LBothRule    ********************/
LBothRule::LBothRule(Prod p1, Prod p2, Prod p3, Prod p4)
{
  prod_1 = p1;
  prod_2 = p2;
  prod_3 = p3;
  prod_4 = p4;

}

LBothRule::LBothRule(const LBothRule & other)
{
  prod_1 = other.prod_1;
  prod_2 = other.prod_2;
  prod_3 = other.prod_3;
  prod_4 = other.prod_4;

}

LBothRule &LBothRule::operator=(const LBothRule & other)
{
  LBothRule tmp(other);
  swap(tmp);
  return *this;
}

void LBothRule::swap(LBothRule & other)
{
  std::swap(prod_1, other.prod_1);
  std::swap(prod_2, other.prod_2);
  std::swap(prod_3, other.prod_3);
  std::swap(prod_4, other.prod_4);

}

LBothRule::~LBothRule()
{

}

void LBothRule::accept(Visitor *v)
{
  v->visitLBothRule(this);
}

LBothRule *LBothRule::clone() const
{
  return new LBothRule(*this);
}



/********************   LRules    ********************/
LRules::LRules(ListRule *p1)
{
  listrule_ = p1;

}

LRules::LRules(const LRules & other)
{
  listrule_ = other.listrule_->clone();

}

LRules &LRules::operator=(const LRules & other)
{
  LRules tmp(other);
  swap(tmp);
  return *this;
}

void LRules::swap(LRules & other)
{
  std::swap(listrule_, other.listrule_);

}

LRules::~LRules()
{
  delete(listrule_);

}

void LRules::accept(Visitor *v)
{
  v->visitLRules(this);
}

LRules *LRules::clone() const
{
  return new LRules(*this);
}




/********************   ListProperty    ********************/

void ListProperty::accept(Visitor *v)
{
  v->visitListProperty(this);
}

ListProperty *ListProperty::clone() const
{
  return new ListProperty(*this);
}

ListProperty* consListProperty(Property* x, ListProperty* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}


/********************   ListRule    ********************/

void ListRule::accept(Visitor *v)
{
  v->visitListRule(this);
}

ListRule *ListRule::clone() const
{
  return new ListRule(*this);
}

ListRule* consListRule(Rule* x, ListRule* xs) {
  xs->insert(xs->begin(), x);
  return xs;
}





