/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitASTSectionSeparator(ASTSectionSeparator *p) {} //abstract class

void PrintAbsyn::visitASTLSectionSeparator(ASTLSectionSeparator *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("--");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTProgram(ASTProgram *p) {} //abstract class

void PrintAbsyn::visitASTLProgram(ASTLProgram *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->astproperties_->accept(this);
  _i_ = 0; p->astsectionseparator_1->accept(this);
  _i_ = 0; p->astaxiom_->accept(this);
  _i_ = 0; p->astsectionseparator_2->accept(this);
  _i_ = 0; p->astrules_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTProperty(ASTProperty *p) {} //abstract class

void PrintAbsyn::visitASTLProperty(ASTLProperty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render(":=");
  visitProd(p->prod_2);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTIgnore(ASTIgnore *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("#ignore");
  visitProd(p->prod_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTProperties(ASTProperties *p) {} //abstract class

void PrintAbsyn::visitASTLProperties(ASTLProperties *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListASTProperty(p->listastproperty_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListASTProperty(ListASTProperty *listastproperty)
{
  iterListASTProperty(listastproperty->begin(), listastproperty->end());
}

void PrintAbsyn::iterListASTProperty(ListASTProperty::const_iterator i, ListASTProperty::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this); render('\n');
  }
  else
  { /* cons */
    (*i)->accept(this); render('\n'); iterListASTProperty(i+1, j);
  }
}

void PrintAbsyn::visitASTAxiom(ASTAxiom *p) {} //abstract class

void PrintAbsyn::visitASTLAxiom(ASTLAxiom *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTRule(ASTRule *p) {} //abstract class

void PrintAbsyn::visitASTLRule(ASTLRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render("->");
  visitProd(p->prod_2);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTLLeftRule(ASTLLeftRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render('<');
  visitProd(p->prod_2);
  render("->");
  visitProd(p->prod_3);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTLRightRule(ASTLRightRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render('>');
  visitProd(p->prod_2);
  render("->");
  visitProd(p->prod_3);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTLBothRule(ASTLBothRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render('<');
  visitProd(p->prod_2);
  render('>');
  visitProd(p->prod_3);
  render("->");
  visitProd(p->prod_4);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitASTRules(ASTRules *p) {} //abstract class

void PrintAbsyn::visitASTLRules(ASTLRules *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListASTRule(p->listastrule_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListASTRule(ListASTRule *listastrule)
{
  iterListASTRule(listastrule->begin(), listastrule->end());
}

void PrintAbsyn::iterListASTRule(ListASTRule::const_iterator i, ListASTRule::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this); render('\n');
  }
  else
  { /* cons */
    (*i)->accept(this); render('\n'); iterListASTRule(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufEscape(c);
  bufAppend('\'');
  bufAppend(' ');
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufEscape(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

void PrintAbsyn::visitProd(String s)
{
  render(s);
}


ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitASTSectionSeparator(ASTSectionSeparator *p) {} //abstract class

void ShowAbsyn::visitASTLSectionSeparator(ASTLSectionSeparator *p)
{
  bufAppend("ASTLSectionSeparator");
}
void ShowAbsyn::visitASTProgram(ASTProgram *p) {} //abstract class

void ShowAbsyn::visitASTLProgram(ASTLProgram *p)
{
  bufAppend('(');
  bufAppend("ASTLProgram");
  bufAppend(' ');
  bufAppend('[');
  if (p->astproperties_)  p->astproperties_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->astsectionseparator_1->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->astaxiom_)  p->astaxiom_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->astsectionseparator_2->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->astrules_)  p->astrules_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitASTProperty(ASTProperty *p) {} //abstract class

void ShowAbsyn::visitASTLProperty(ASTLProperty *p)
{
  bufAppend('(');
  bufAppend("ASTLProperty");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(')');
}
void ShowAbsyn::visitASTIgnore(ASTIgnore *p)
{
  bufAppend('(');
  bufAppend("ASTIgnore");
  bufAppend(' ');
  visitProd(p->prod_);
  bufAppend(')');
}
void ShowAbsyn::visitASTProperties(ASTProperties *p) {} //abstract class

void ShowAbsyn::visitASTLProperties(ASTLProperties *p)
{
  bufAppend('(');
  bufAppend("ASTLProperties");
  bufAppend(' ');
  bufAppend('[');
  if (p->listastproperty_)  p->listastproperty_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListASTProperty(ListASTProperty *listastproperty)
{
  for (ListASTProperty::const_iterator i = listastproperty->begin() ; i != listastproperty->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listastproperty->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitASTAxiom(ASTAxiom *p) {} //abstract class

void ShowAbsyn::visitASTLAxiom(ASTLAxiom *p)
{
  bufAppend('(');
  bufAppend("ASTLAxiom");
  bufAppend(' ');
  visitProd(p->prod_);
  bufAppend(')');
}
void ShowAbsyn::visitASTRule(ASTRule *p) {} //abstract class

void ShowAbsyn::visitASTLRule(ASTLRule *p)
{
  bufAppend('(');
  bufAppend("ASTLRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(')');
}
void ShowAbsyn::visitASTLLeftRule(ASTLLeftRule *p)
{
  bufAppend('(');
  bufAppend("ASTLLeftRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(' ');
  visitProd(p->prod_3);
  bufAppend(')');
}
void ShowAbsyn::visitASTLRightRule(ASTLRightRule *p)
{
  bufAppend('(');
  bufAppend("ASTLRightRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(' ');
  visitProd(p->prod_3);
  bufAppend(')');
}
void ShowAbsyn::visitASTLBothRule(ASTLBothRule *p)
{
  bufAppend('(');
  bufAppend("ASTLBothRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(' ');
  visitProd(p->prod_3);
  bufAppend(' ');
  visitProd(p->prod_4);
  bufAppend(')');
}
void ShowAbsyn::visitASTRules(ASTRules *p) {} //abstract class

void ShowAbsyn::visitASTLRules(ASTLRules *p)
{
  bufAppend('(');
  bufAppend("ASTLRules");
  bufAppend(' ');
  bufAppend('[');
  if (p->listastrule_)  p->listastrule_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListASTRule(ListASTRule *listastrule)
{
  for (ListASTRule::const_iterator i = listastrule->begin() ; i != listastrule->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listastrule->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufEscape(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufEscape(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

void ShowAbsyn::visitProd(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}



