/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitSectionSeparator(SectionSeparator *p) {} //abstract class

void PrintAbsyn::visitLSectionSeparator(LSectionSeparator *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render("--");

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitLProgram(LProgram *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->properties_->accept(this);
  _i_ = 0; p->sectionseparator_1->accept(this);
  _i_ = 0; p->axiom_->accept(this);
  _i_ = 0; p->sectionseparator_2->accept(this);
  _i_ = 0; p->rules_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitProperty(Property *p) {} //abstract class

void PrintAbsyn::visitLIProperty(LIProperty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_);
  render(":=");
  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLDProperty(LDProperty *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_);
  render(":=");
  visitDouble(p->double_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitProperties(Properties *p) {} //abstract class

void PrintAbsyn::visitLProperties(LProperties *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListProperty(p->listproperty_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListProperty(ListProperty *listproperty)
{
  iterListProperty(listproperty->begin(), listproperty->end());
}

void PrintAbsyn::iterListProperty(ListProperty::const_iterator i, ListProperty::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this); render('\n');
  }
  else
  { /* cons */
    (*i)->accept(this); render('\n'); iterListProperty(i+1, j);
  }
}

void PrintAbsyn::visitAxiom(Axiom *p) {} //abstract class

void PrintAbsyn::visitLAxiom(LAxiom *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRule(Rule *p) {} //abstract class

void PrintAbsyn::visitLRule(LRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render("->");
  visitProd(p->prod_2);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLLeftRule(LLeftRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render('<');
  visitProd(p->prod_2);
  render("->");
  visitProd(p->prod_3);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLRightRule(LRightRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render('>');
  visitProd(p->prod_2);
  render("->");
  visitProd(p->prod_3);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLBothRule(LBothRule *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitProd(p->prod_1);
  render('<');
  visitProd(p->prod_2);
  render('>');
  visitProd(p->prod_3);
  render("->");
  visitProd(p->prod_4);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitRules(Rules *p) {} //abstract class

void PrintAbsyn::visitLRules(LRules *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; visitListRule(p->listrule_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitListRule(ListRule *listrule)
{
  iterListRule(listrule->begin(), listrule->end());
}

void PrintAbsyn::iterListRule(ListRule::const_iterator i, ListRule::const_iterator j)
{
  if (i == j) return;
  if (i == j-1)
  { /* last */
    (*i)->accept(this); render('\n');
  }
  else
  { /* cons */
    (*i)->accept(this); render('\n'); iterListRule(i+1, j);
  }
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufEscape(c);
  bufAppend('\'');
  bufAppend(' ');
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufEscape(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

void PrintAbsyn::visitProd(String s)
{
  render(s);
}


ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitSectionSeparator(SectionSeparator *p) {} //abstract class

void ShowAbsyn::visitLSectionSeparator(LSectionSeparator *p)
{
  bufAppend("LSectionSeparator");
}
void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitLProgram(LProgram *p)
{
  bufAppend('(');
  bufAppend("LProgram");
  bufAppend(' ');
  bufAppend('[');
  if (p->properties_)  p->properties_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->sectionseparator_1->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->axiom_)  p->axiom_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  p->sectionseparator_2->accept(this);
  bufAppend(' ');
  bufAppend('[');
  if (p->rules_)  p->rules_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitProperty(Property *p) {} //abstract class

void ShowAbsyn::visitLIProperty(LIProperty *p)
{
  bufAppend('(');
  bufAppend("LIProperty");
  bufAppend(' ');
  visitProd(p->prod_);
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitLDProperty(LDProperty *p)
{
  bufAppend('(');
  bufAppend("LDProperty");
  bufAppend(' ');
  visitProd(p->prod_);
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitProperties(Properties *p) {} //abstract class

void ShowAbsyn::visitLProperties(LProperties *p)
{
  bufAppend('(');
  bufAppend("LProperties");
  bufAppend(' ');
  bufAppend('[');
  if (p->listproperty_)  p->listproperty_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListProperty(ListProperty *listproperty)
{
  for (ListProperty::const_iterator i = listproperty->begin() ; i != listproperty->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listproperty->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitAxiom(Axiom *p) {} //abstract class

void ShowAbsyn::visitLAxiom(LAxiom *p)
{
  bufAppend('(');
  bufAppend("LAxiom");
  bufAppend(' ');
  visitProd(p->prod_);
  bufAppend(')');
}
void ShowAbsyn::visitRule(Rule *p) {} //abstract class

void ShowAbsyn::visitLRule(LRule *p)
{
  bufAppend('(');
  bufAppend("LRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(')');
}
void ShowAbsyn::visitLLeftRule(LLeftRule *p)
{
  bufAppend('(');
  bufAppend("LLeftRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(' ');
  visitProd(p->prod_3);
  bufAppend(')');
}
void ShowAbsyn::visitLRightRule(LRightRule *p)
{
  bufAppend('(');
  bufAppend("LRightRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(' ');
  visitProd(p->prod_3);
  bufAppend(')');
}
void ShowAbsyn::visitLBothRule(LBothRule *p)
{
  bufAppend('(');
  bufAppend("LBothRule");
  bufAppend(' ');
  visitProd(p->prod_1);
  bufAppend(' ');
  visitProd(p->prod_2);
  bufAppend(' ');
  visitProd(p->prod_3);
  bufAppend(' ');
  visitProd(p->prod_4);
  bufAppend(')');
}
void ShowAbsyn::visitRules(Rules *p) {} //abstract class

void ShowAbsyn::visitLRules(LRules *p)
{
  bufAppend('(');
  bufAppend("LRules");
  bufAppend(' ');
  bufAppend('[');
  if (p->listrule_)  p->listrule_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitListRule(ListRule *listrule)
{
  for (ListRule::const_iterator i = listrule->begin() ; i != listrule->end() ; ++i)
  {
    (*i)->accept(this);
    if (i != listrule->end() - 1) bufAppend(", ");
  }
}

void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufEscape(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufEscape(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}

void ShowAbsyn::visitProd(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}



