/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitSectionSeparator(SectionSeparator *t) {} //abstract class
void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitProperty(Property *t) {} //abstract class
void Skeleton::visitProperties(Properties *t) {} //abstract class
void Skeleton::visitAxiom(Axiom *t) {} //abstract class
void Skeleton::visitRule(Rule *t) {} //abstract class
void Skeleton::visitRules(Rules *t) {} //abstract class

void Skeleton::visitLSectionSeparator(LSectionSeparator *l_section_separator)
{
  /* Code For LSectionSeparator Goes Here */


}

void Skeleton::visitLProgram(LProgram *l_program)
{
  /* Code For LProgram Goes Here */

  if (l_program->properties_) l_program->properties_->accept(this);
  if (l_program->sectionseparator_1) l_program->sectionseparator_1->accept(this);
  if (l_program->axiom_) l_program->axiom_->accept(this);
  if (l_program->sectionseparator_2) l_program->sectionseparator_2->accept(this);
  if (l_program->rules_) l_program->rules_->accept(this);

}

void Skeleton::visitLIProperty(LIProperty *li_property)
{
  /* Code For LIProperty Goes Here */

  visitProd(li_property->prod_);
  visitInteger(li_property->integer_);

}

void Skeleton::visitLDProperty(LDProperty *ld_property)
{
  /* Code For LDProperty Goes Here */

  visitProd(ld_property->prod_);
  visitDouble(ld_property->double_);

}

void Skeleton::visitLProperties(LProperties *l_properties)
{
  /* Code For LProperties Goes Here */

  if (l_properties->listproperty_) l_properties->listproperty_->accept(this);

}

void Skeleton::visitLAxiom(LAxiom *l_axiom)
{
  /* Code For LAxiom Goes Here */

  visitProd(l_axiom->prod_);

}

void Skeleton::visitLRule(LRule *l_rule)
{
  /* Code For LRule Goes Here */

  visitProd(l_rule->prod_1);
  visitProd(l_rule->prod_2);

}

void Skeleton::visitLLeftRule(LLeftRule *l_left_rule)
{
  /* Code For LLeftRule Goes Here */

  visitProd(l_left_rule->prod_1);
  visitProd(l_left_rule->prod_2);
  visitProd(l_left_rule->prod_3);

}

void Skeleton::visitLRightRule(LRightRule *l_right_rule)
{
  /* Code For LRightRule Goes Here */

  visitProd(l_right_rule->prod_1);
  visitProd(l_right_rule->prod_2);
  visitProd(l_right_rule->prod_3);

}

void Skeleton::visitLBothRule(LBothRule *l_both_rule)
{
  /* Code For LBothRule Goes Here */

  visitProd(l_both_rule->prod_1);
  visitProd(l_both_rule->prod_2);
  visitProd(l_both_rule->prod_3);
  visitProd(l_both_rule->prod_4);

}

void Skeleton::visitLRules(LRules *l_rules)
{
  /* Code For LRules Goes Here */

  if (l_rules->listrule_) l_rules->listrule_->accept(this);

}


void Skeleton::visitListProperty(ListProperty *list_property)
{
  for (ListProperty::iterator i = list_property->begin() ; i != list_property->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListRule(ListRule *list_rule)
{
  for (ListRule::iterator i = list_rule->begin() ; i != list_rule->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}

void Skeleton::visitProd(Prod x)
{
  /* Code for Prod Goes Here */
}



