/* File generated by the BNF Converter (bnfc 2.9.5). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitASTSectionSeparator(ASTSectionSeparator *t) {} //abstract class
void Skeleton::visitASTProgram(ASTProgram *t) {} //abstract class
void Skeleton::visitASTProperty(ASTProperty *t) {} //abstract class
void Skeleton::visitASTProperties(ASTProperties *t) {} //abstract class
void Skeleton::visitASTAxiom(ASTAxiom *t) {} //abstract class
void Skeleton::visitASTRule(ASTRule *t) {} //abstract class
void Skeleton::visitASTRules(ASTRules *t) {} //abstract class

void Skeleton::visitASTLSectionSeparator(ASTLSectionSeparator *astl_section_separator)
{
  /* Code For ASTLSectionSeparator Goes Here */


}

void Skeleton::visitASTLProgram(ASTLProgram *astl_program)
{
  /* Code For ASTLProgram Goes Here */

  if (astl_program->astproperties_) astl_program->astproperties_->accept(this);
  if (astl_program->astsectionseparator_1) astl_program->astsectionseparator_1->accept(this);
  if (astl_program->astaxiom_) astl_program->astaxiom_->accept(this);
  if (astl_program->astsectionseparator_2) astl_program->astsectionseparator_2->accept(this);
  if (astl_program->astrules_) astl_program->astrules_->accept(this);

}

void Skeleton::visitASTLIProperty(ASTLIProperty *astli_property)
{
  /* Code For ASTLIProperty Goes Here */

  visitProd(astli_property->prod_);
  visitInteger(astli_property->integer_);

}

void Skeleton::visitASTLDProperty(ASTLDProperty *astld_property)
{
  /* Code For ASTLDProperty Goes Here */

  visitProd(astld_property->prod_);
  visitDouble(astld_property->double_);

}

void Skeleton::visitASTIgnore(ASTIgnore *ast_ignore)
{
  /* Code For ASTIgnore Goes Here */

  visitProd(ast_ignore->prod_);

}

void Skeleton::visitASTLProperties(ASTLProperties *astl_properties)
{
  /* Code For ASTLProperties Goes Here */

  if (astl_properties->listastproperty_) astl_properties->listastproperty_->accept(this);

}

void Skeleton::visitASTLAxiom(ASTLAxiom *astl_axiom)
{
  /* Code For ASTLAxiom Goes Here */

  visitProd(astl_axiom->prod_);

}

void Skeleton::visitASTLRule(ASTLRule *astl_rule)
{
  /* Code For ASTLRule Goes Here */

  visitProd(astl_rule->prod_1);
  visitProd(astl_rule->prod_2);

}

void Skeleton::visitASTLLeftRule(ASTLLeftRule *astl_left_rule)
{
  /* Code For ASTLLeftRule Goes Here */

  visitProd(astl_left_rule->prod_1);
  visitProd(astl_left_rule->prod_2);
  visitProd(astl_left_rule->prod_3);

}

void Skeleton::visitASTLRightRule(ASTLRightRule *astl_right_rule)
{
  /* Code For ASTLRightRule Goes Here */

  visitProd(astl_right_rule->prod_1);
  visitProd(astl_right_rule->prod_2);
  visitProd(astl_right_rule->prod_3);

}

void Skeleton::visitASTLBothRule(ASTLBothRule *astl_both_rule)
{
  /* Code For ASTLBothRule Goes Here */

  visitProd(astl_both_rule->prod_1);
  visitProd(astl_both_rule->prod_2);
  visitProd(astl_both_rule->prod_3);
  visitProd(astl_both_rule->prod_4);

}

void Skeleton::visitASTLRules(ASTLRules *astl_rules)
{
  /* Code For ASTLRules Goes Here */

  if (astl_rules->listastrule_) astl_rules->listastrule_->accept(this);

}


void Skeleton::visitListASTProperty(ListASTProperty *list_ast_property)
{
  for (ListASTProperty::iterator i = list_ast_property->begin() ; i != list_ast_property->end() ; ++i)
  {
    (*i)->accept(this);
  }
}

void Skeleton::visitListASTRule(ListASTRule *list_ast_rule)
{
  for (ListASTRule::iterator i = list_ast_rule->begin() ; i != list_ast_rule->end() ; ++i)
  {
    (*i)->accept(this);
  }
}


void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}

void Skeleton::visitProd(Prod x)
{
  /* Code for Prod Goes Here */
}



