#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer predecessors_Buffer {
    int[] predecessors;
};

layout(std430, binding = 1) readonly buffer look_back_Buffer {
    int[] look_back;
};

layout(std430, binding = 2) readonly buffer successors_sizes_Buffer {
    int[] successors_sizes;
};

layout(std430, binding = 3) readonly buffer successors_offsets_Buffer {
    int[] successors_offsets;
};

layout(std430, binding = 4) readonly buffer successors_data_Buffer {
    int[] successors_data;
};

layout(std430, binding = 5) readonly buffer left_context_sizes_Buffer {
    int[] left_context_sizes;
};

layout(std430, binding = 6) readonly buffer left_context_offsets_Buffer {
    int[] left_context_offsets;
};

layout(std430, binding = 7) readonly buffer left_context_data_Buffer {
    int[] left_context_data;
};

layout(std430, binding = 8) readonly buffer right_context_sizes_Buffer {
    int[] right_context_sizes;
};

layout(std430, binding = 9) readonly buffer right_context_offsets_Buffer {
    int[] right_context_offsets;
};

layout(std430, binding = 10) readonly buffer right_context_data_Buffer {
    int[] right_context_data;
};

layout(std430, binding = 11) readonly buffer inputBufferBuffer {
    int inputBuffer[];
};

layout(std430, binding = 12) buffer productionNumberOutputBuffer {
    int productionNumberOutput[];
};

layout(std430, binding = 13) buffer productionSizeOutputBuffer {
    int productionSizeOutput[];
};

layout(std430, binding = 14) readonly buffer ignored_Buffer {
    int[] ignored;
};

layout(std430, binding = 15) readonly buffer inputBufferLookbackBuffer {
    int[] inputBufferLookback;
};

uniform int numberOfProductions;
uniform int wholeInputSize;
uniform int ignoredSize;

bool amIIgnored(int letter) {
    // Check if the letter is in the ignored list
    for (int i = 0; i < ignoredSize; i++) {
        if (letter == ignored[i]) {
            return true;
        }
    }
    return false;
}

bool checkLeftContext(int productionIndex, int index) {
    int leftContextSize = left_context_sizes[productionIndex];
    if (leftContextSize == 0) {
        return true;
    }

    int leftContextStart = left_context_offsets[productionIndex];
    int leftContextEnd = leftContextStart + leftContextSize;

    int currentWordIndex = index - 1;
    int currentContextIndex = leftContextEnd - 1;
    int stepToPerform = leftContextSize;

    while (stepToPerform > 0 && currentWordIndex >= 0) {
        if (inputBuffer[currentWordIndex] == 93 /* ] */) {
            // Jump in the tree using LookBack table
            currentWordIndex += inputBufferLookback[currentWordIndex];
        } else if (inputBuffer[currentWordIndex] == 91 /* [ */) {
            // Jump in the tree to the beginning of the branch
            currentWordIndex -= 1;
        } else if (amIIgnored(inputBuffer[currentWordIndex])) {
            // Ignore ignored letter
            currentWordIndex -= 1;
        } else {
            if (inputBuffer[currentWordIndex] != left_context_data[currentContextIndex]) {
                return false;
            }
            currentWordIndex -= 1;
            currentContextIndex -= 1;
            stepToPerform -= 1;
        }
    }

    return true;
}

bool checkRightContext(int productionIndex, int index) {
    int rightContextSize = right_context_sizes[productionIndex];
    if (right_context_sizes[productionIndex] == 0) {
        return true;
    }

    int rightContextStart = right_context_offsets[productionIndex];
    int rightContextEnd = rightContextStart + rightContextSize;

    int currentWordIndex = index + 1;
    int currentContextIndex = rightContextStart;
    int stepToPerform = rightContextSize;

    while (stepToPerform > 0 && currentWordIndex < wholeInputSize) {
        if (inputBuffer[currentWordIndex] == 93 /* ] */) {
            // Jump in the tree to the end of the branch
            currentWordIndex += 1;
        } else if (inputBuffer[currentWordIndex] == 91 /* [ */) {
            // Jump in the tree using LookBack table
            currentWordIndex += inputBufferLookback[currentWordIndex];
        } else if (amIIgnored(inputBuffer[currentWordIndex])) {
            // Ignore ignored letter
            currentWordIndex += 1;
        } else {
            if (inputBuffer[currentWordIndex] != right_context_data[currentContextIndex]) {
                return false;
            }
            currentWordIndex += 1;
            currentContextIndex += 1;
            stepToPerform += 1;
        }
    }

    return true;
}

bool checkIfproductionIsMatching(int productionIndex, int index) {
    int letter = inputBuffer[index];

    // Check if the letter matches the predecessor
    if (letter != predecessors[productionIndex]) {
        return false;
    }

    // Check if the left context matches
    if (!checkLeftContext(productionIndex, index)) {
        return false;
    }

    // Check if the right context matches
    if (!checkRightContext(productionIndex, index)) {
        return false;
    }

    return true;
}

void main() {
    int index = int(gl_GlobalInvocationID.x);

    for (int p = 0; p < numberOfProductions; p++) {
        if (checkIfproductionIsMatching(p, index)) {
            productionNumberOutput[index] = p;
            productionSizeOutput[index] = successors_sizes[p];
            return;
        }
    }

    // If no production matches, set the output to -1
    productionNumberOutput[index] = -1;
    productionSizeOutput[index] = 1;
}
