#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer predecessors_Buffer {
    int[] predecessors;
};

layout(std430, binding = 1) readonly buffer look_back_Buffer {
    int[] look_back;
};

layout(std430, binding = 2) readonly buffer successors_sizes_Buffer {
    int[] successors_sizes;
};

layout(std430, binding = 3) readonly buffer successors_offsets_Buffer {
    int[] successors_offsets;
};

layout(std430, binding = 4) readonly buffer successors_data_Buffer {
    int[] successors_data;
};

layout(std430, binding = 5) readonly buffer left_context_sizes_Buffer {
    int[] left_context_sizes;
};

layout(std430, binding = 6) readonly buffer left_context_offsets_Buffer {
    int[] left_context_offsets;
};

layout(std430, binding = 7) readonly buffer left_context_data_Buffer {
    int[] left_context_data;
};

layout(std430, binding = 8) readonly buffer right_context_sizes_Buffer {
    int[] right_context_sizes;
};

layout(std430, binding = 9) readonly buffer right_context_offsets_Buffer {
    int[] right_context_offsets;
};

layout(std430, binding = 10) readonly buffer right_context_data_Buffer {
    int[] right_context_data;
};

layout(std430, binding = 11) readonly buffer inputBufferBuffer {
    int inputBuffer[];
};

layout(std430, binding = 12) buffer productionNumberOutputBuffer {
    int productionNumberOutput[];
};

layout(std430, binding = 13) buffer productionSizeOutputBuffer {
    int productionSizeOutput[];
};

uniform int numberOfProductions;
uniform int wholeInputSize;

bool checkLeftContext(int productionIndex, int index) {
    // Check if left context matches
    int leftContextSize = left_context_sizes[productionIndex];
    int leftContextStart = left_context_offsets[productionIndex];
    int leftContextEnd = leftContextStart + leftContextSize;
    // Get the beginning og the input to compare with the left context
    int leftIndexPos = index - leftContextSize;
    if (leftIndexPos < 0) {
        // we jumped over the beginning of the input
        return false;
    }
    for (int i = leftContextStart; i < leftContextEnd; i++) {
        if (inputBuffer[leftIndexPos] != left_context_data[i]) {
            return false;
        }
        leftIndexPos++;
    }
    return true;
}

bool checkRightContext(int productionIndex, int index) {
    // Check if right context matches
    int rightContextSize = right_context_sizes[productionIndex];
    if (right_context_sizes[productionIndex] == 0) {
        return true;
    }

    int rightContextStart = right_context_offsets[productionIndex];
    int rightContextEnd = rightContextStart + rightContextSize;
    int rightIndexPos = index + 1;
    if (rightIndexPos + rightContextSize > wholeInputSize) {
        // we jumped over the end of the input
        return false;
    }
    for (int i = rightContextStart; i < rightContextEnd; i++) {
        if (inputBuffer[rightIndexPos] != right_context_data[i]) {
            return false;
        }
        rightIndexPos++;
    }
    return true;
}

bool checkIfproductionIsMatching(int productionIndex, int index) {
    int letter = inputBuffer[index];

    // Check if the letter matches the predecessor
    if (letter != predecessors[productionIndex]) {
        return false;
    }

    // Check if the left context matches
    if (!checkLeftContext(productionIndex, index)) {
        return false;
    }

    // Check if the right context matches
    if (!checkRightContext(productionIndex, index)) {
        return false;
    }

    return true;
}

void main() {
    int index = int(gl_GlobalInvocationID.x);

    for (int p = 0; p < numberOfProductions; p++) {
        if (checkIfproductionIsMatching(p, index)) {
            productionNumberOutput[index] = p;
            productionSizeOutput[index] = successors_sizes[p];
            return;
        }
    }

    // If no production matches, set the output to -1
    productionNumberOutput[index] = -1;
    productionSizeOutput[index] = 1;
}
