#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// this buffer is bigger, as number of letters is bigger
layout(std430, binding = 0) readonly buffer InputTransformations {
    mat4 inputTransformations[];
};

// this buffer is smaller, as number of instances is smaller
layout(std430, binding = 1) buffer OutputTransformation {
    mat4 outputTransformations[];
};

// offsets for each instance - inclusive prefix sum of instance so far
layout(std430, binding = 2) readonly buffer OffsetsInput {
    int offsetsInput[];
};

layout(std430, binding = 3) readonly buffer InstanceStepInput {
    float instanceStepInput[];
};

layout(std430, binding = 4) readonly buffer InputColorIndex {
    int inputColorIndex[];
};

layout(std430, binding = 5) buffer OutputColorIndex {
    int outputColorIndex[];
};

uniform mat4 common_turtle_matrix;
uniform mat4 common_cube_matrix_a;
uniform mat4 common_cube_matrix_c;
uniform float step;
uniform int scale_branch;

mat4 common_cube_matrix_b(int instanceId) {
    float myStep = instanceStepInput[instanceId];
    float myScale = 1.0;
    if (scale_branch > 0) {
        myScale = myStep;
    }

    return mat4(
        vec4(-step * myStep, 0.0, 0.0, 0.0),
        vec4(0.0, myScale, 0.0, 0.0),
        vec4(0.0, 0.0, myScale, 0.0),
        vec4(0.0, 0.0, 0.0, 1.0)
    );
}

mat4 common_cube_matrix(int instanceId) {
    return common_cube_matrix_a * common_cube_matrix_b(instanceId) * common_cube_matrix_c;
}

int mySumFactor(int index) {
    if (index == 0) {
        return offsetsInput[0];
    }
    return offsetsInput[index] - offsetsInput[index - 1];
}

void main() {
    int index = int(gl_GlobalInvocationID.x);

    if (mySumFactor(index) == 0) {
        return;
    }

    // only if I'm F
    int hoManyInstancesBeforeMe = offsetsInput[index] - 1;
    // rewrite from input to output
    outputTransformations[hoManyInstancesBeforeMe] = transpose(inputTransformations[index] * common_turtle_matrix) * common_cube_matrix(index);
    // rewrite from input to output
    outputColorIndex[hoManyInstancesBeforeMe] = inputColorIndex[index];
}
