#version 430

#define DRAWABLE_CHAR 70 /* F */

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 1) buffer OutputBuffer {
    int outputBuffer[];
};

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (inputBuffer[index] == DRAWABLE_CHAR) {
        outputBuffer[index] = 1;
    } else {
        outputBuffer[index] = 0;
    }
}
