#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 1) buffer OutputBuffer {
    int outputBuffer[];
};

uniform int char_to_find_one;
uniform int char_to_find_minus_one;

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (inputBuffer[index] == char_to_find_one) {
        outputBuffer[index] = 1;
    } else if (inputBuffer[index] == char_to_find_minus_one) {
        outputBuffer[index] = -1;
    } else {
        outputBuffer[index] = 0;
    }
}
