#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) buffer InputOutputBuffer {
    int inputOutputBuffer[];
};

uniform int step;

void main() {
    uint index = gl_GlobalInvocationID.x;
    uint two_pow_step_m_1 = 1 << (step - 1);

    if (index >= two_pow_step_m_1) {
        int t = inputOutputBuffer[index - two_pow_step_m_1];
        memoryBarrierShared();
        inputOutputBuffer[index] = t + inputOutputBuffer[index];
    } else {
        memoryBarrierShared();
    }
}
