#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer InputTransformations {
    mat4 inputTransformations[];
};

layout(std430, binding = 1) buffer OutputTransformation {
    mat4 outputTransformations[];
};

layout(std430, binding = 2) readonly buffer InputJumps {
    int inputJumps[];
};

layout(std430, binding = 3) buffer OutputJumps {
    int outputJumps[];
};

uniform int epoch;

void init_jumps(int index) {
    if (inputJumps[index] >= 0) {
        // if the LookBack table was zero or positive, it means that we are not ]
        // for index=0 it will be -1 which is expected
        outputJumps[index] = index - 1;
    } else {
        // if the LookBack table was negative, it means that we are ] and we should jump back
        outputJumps[index] = index + inputJumps[index];
    }
}

void init_transformations(int index) {
    // rewrite from input to output
    outputTransformations[index] = inputTransformations[index];
}

void multiply_transformations(int index, int previousIndex) {
    mat4 myTransformation = inputTransformations[index];
    mat4 previousTransformation = inputTransformations[previousIndex];

    // Take two transformations and multiply them
    outputTransformations[index] = myTransformation * previousTransformation;
}

void update_jumps(int index, int previousIndex) {
    // Father of my father is my father's father (grandfather)
    outputJumps[index] = inputJumps[previousIndex];
}

void main() {
    int index = int(gl_GlobalInvocationID.x);

    if (epoch == 0) {
        // rewrite Look Back into the output with adjustments
        init_jumps(index);
        init_transformations(index);
    } else {
        // run multiplication
        int previousIndex = inputJumps[index];
        if (previousIndex < 0) {
            // if the jump was negative, it means we already hit the root of the tree
            return;
        }

        multiply_transformations(index, previousIndex);
        update_jumps(index, previousIndex);
    }
}
