#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 1) buffer OutputBuffer {
    int outputBuffer[];
};

uniform int step;

void main() {
    uint index = gl_GlobalInvocationID.x;
    uint two_pow_step_m_1 = 1 << (step - 1);

    if (index >= two_pow_step_m_1) {
        outputBuffer[index] = inputBuffer[index - two_pow_step_m_1] + inputBuffer[index];
    } else {
        outputBuffer[index] = inputBuffer[index];
    }
}
