#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer ProductionOffsets {
    int offsets[];
};

layout(std430, binding = 1) readonly buffer ProductionSizes {
    int sizes[];
};

layout(std430, binding = 2) readonly buffer Productions {
    int productions[];
};

layout(std430, binding = 3) readonly buffer InputBuffer {
    int inputBuffer[];
};

layout(std430, binding = 4) readonly buffer InputOffsetBuffer {
    int inputOffsetBuffer[];
};

layout(std430, binding = 5) buffer OutputBuffer {
    int outputBuffer[];
};

layout(std430, binding = 6) readonly buffer ProductionLookBacks {
    int lookBacks[];
};

layout(std430, binding = 7) readonly buffer InputLookBackBuffer {
    int inputLookBackBuffer[];
};

layout(std430, binding = 8) buffer OutputLookBackBuffer {
    int outputLookBackBuffer[];
};

void main() {
    // my invocation id
    int index = int(gl_GlobalInvocationID.x);
    // letter to transform
    int letter = inputBuffer[index];

    // size of the production
    int productionSize = sizes[letter];
    // where to look to a production in productions
    int productionOffset = offsets[letter];

    if (productionSize < 0 || productionOffset < 0) {
        // if the production size is negative, it means that the letter transforms to itself
        // inputOffsetBuffer[index] - 1 because inputOffsetBuffer[index] points to the end of our result space
        int resultIdx = inputOffsetBuffer[index] - 1;
        outputBuffer[resultIdx] = letter;
        // We account the calculations for both brackets
        if (letter == 93 /* ] */ || letter == 91 /* [ */) {
            int my_PS = inputOffsetBuffer[index] - 1;
            int lookBackIndex = index + inputLookBackBuffer[index];
            int my_lookBack_PS = inputOffsetBuffer[lookBackIndex] - 1;
            int lookBackValue = my_lookBack_PS - my_PS;
            outputLookBackBuffer[resultIdx] = lookBackValue;
        }
        return;
    }

    // where to start my result
    int resultIdx = inputOffsetBuffer[index] - productionSize;

    // walk through the production
    for (int produtionIt = productionOffset; produtionIt < productionOffset + productionSize; produtionIt++) {
        // place the production in the output buffer
        outputBuffer[resultIdx] = productions[produtionIt];
        // place the look back in the output look back buffer
        outputLookBackBuffer[resultIdx] = lookBacks[produtionIt];
        resultIdx++;
    }
}
