#version 430

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer ProductionOffsets {
    int offsets[];
};

layout(std430, binding = 1) readonly buffer ProductionSizes {
    int sizes[];
};

layout(std430, binding = 2) readonly buffer Productions {
    int productions[];
};

layout(std430, binding = 3) buffer InputOutputBuffer {
    int inputOutputBuffer[];
};

void main() {
    uint index = gl_GlobalInvocationID.x;
    int letter = inputOutputBuffer[index];
    int productionSize = sizes[letter];

    if (productionSize < 0) {
        productionSize = 1;
    }

    inputOutputBuffer[index] = productionSize;
}
