#!/bin/bash

function LOG() {
    echo -e "\e[32m[$1]\e[0m $2"
}

LOG "START" "Generating C++ code from LSystem.cf"
bnfc --cpp -m -o src-temp LSystem.cf > /dev/null 2>&1 || exit 1
LOG "END" "Done generating C++ code from LSystem.cf"

LOG "START" "Running C++ code generation"
pushd src-temp > /dev/null || exit 1
make > /dev/null 2>&1 || exit 1
popd > /dev/null || exit 1
LOG "END" "Done running C++ code generation"

LOG "START" "Resetting src directory"
rm -rf src
mkdir -p src
LOG "END" "Done resetting src directory"

LOG "START" "Copying generated C++ code to src"
cp src-temp/*.C src
cp src-temp/*.H src
LOG "END" "Done copying generated C++ code to src"

LOG "START" "Generated C/H files:"
ls src
LOG "END" "Done listing generated C/H files"

LOG "START" "Generating CMakeLists.txt"
file_list=$(ls src | sed 's/^/src\//' | tr '\n' ' ')
echo "Generated files list:"
echo "$file_list"
{
  echo "# THIS FILE WAS AUTO-GENERATED. DO NOT EDIT MANUALLY!";
  echo "# Generated by reset-grammar.sh";
  echo "# Date: $(date)";
  sed "s#GENERATED_SOURCES_TEMPLATE_PARAMETER#$file_list#" CMakeLists.txt.template;
} > CMakeLists.txt
LOG "END" "Done generating CMakeLists.txt"

LOG "START" "Cleaning up"
rm -rf src-temp
LOG "END" "Done cleaning up"
