#!/bin/bash

function LOG() {
    echo -e "\e[32m[$1]\e[0m $2"
}

function ERROR() {
    echo -e "\e[31m[ERROR]\e[0m $1"
    exit 1
}

LOG "START" "Generating C++ code from LSystem.cf"
bnfc --cpp -m -o src-temp LSystem.cf > /dev/null 2>&1 || ERROR "Failed to generate C++ code from LSystem.cf"
LOG "END" "Done generating C++ code from LSystem.cf"

LOG "START" "Running C++ code generation"
pushd src-temp > /dev/null || ERROR "Failed to enter src-temp directory"
make > /dev/null 2>&1 || ERROR "Failed to build generated C++ code"
popd > /dev/null || ERROR "Failed to return to the original directory"
LOG "END" "Done running C++ code generation"

LOG "START" "Resetting src directory"
rm -rf src || ERROR "Failed to remove src directory"
mkdir -p src || ERROR "Failed to create src directory"
LOG "END" "Done resetting src directory"

LOG "START" "Copying generated C++ code to src"
cp src-temp/*.C src || ERROR "Failed to copy .C files to src"
cp src-temp/*.H src || ERROR "Failed to copy .H files to src"
LOG "END" "Done copying generated C++ code to src"

LOG "START" "Generated C/H files:"
ls src || ERROR "Failed to list files in src directory"
LOG "END" "Done listing generated C/H files"

LOG "START" "Generating CMakeLists.txt"
file_list=$(ls src | sed 's/^/src\//' | tr '\n' ' ') || ERROR "Failed to generate file list for CMakeLists.txt"
echo "Generated files list:"
echo "$file_list"
{
  echo "# THIS FILE WAS AUTO-GENERATED. DO NOT EDIT MANUALLY!";
  echo "# Generated by reset-grammar.sh";
  echo "# Date: $(date)";
  sed "s#GENERATED_SOURCES_TEMPLATE_PARAMETER#$file_list#" CMakeLists.txt.template || ERROR "Failed to process CMakeLists.txt.template"
} > CMakeLists.txt || ERROR "Failed to write CMakeLists.txt"
LOG "END" "Done generating CMakeLists.txt"

LOG "START" "Cleaning up"
rm -rf src-temp || ERROR "Failed to clean up src-temp directory"
LOG "END" "Done cleaning up"